name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.actor }}/frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.actor }}/backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push AI Service image
      uses: docker/build-push-action@v5
      with:
        context: ./ai_service
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.actor }}/ai-service:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Azure Container Instances
      if: github.ref == 'refs/heads/main'
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.AZURE_DNS_NAME }}
        location: ${{ secrets.AZURE_LOCATION }}
        image: ${{ env.REGISTRY }}/${{ github.actor }}/frontend:${{ github.sha }}
        registry-login-server: ${{ env.REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        name: frontend-container
        cpu: 1
        memory: 1
        ports: 8081

    - name: Deploy Backend to Azure App Service
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_APP_NAME_BACKEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        images: ${{ env.REGISTRY }}/${{ github.actor }}/backend:${{ github.sha }}

    - name: Deploy AI Service to Azure Container Instances
      if: github.ref == 'refs/heads/main'
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.AZURE_DNS_NAME }}-ai
        location: ${{ secrets.AZURE_LOCATION }}
        image: ${{ env.REGISTRY }}/${{ github.actor }}/ai-service:${{ github.sha }}
        registry-login-server: ${{ env.REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        name: ai-service-container
        cpu: 2
        memory: 4
        ports: 8000 